### ISSUE TITLE
Can you add new webpage hub?

### ISSUE THREAD

**Issue by Neizan93** [kokarn/ARK-Dev-Tracker#19] opened 2015-12-11 13:39 UTC

**Comment by Neizan93** [comment] 2015-12-11 13:40
can you add unreal engine forums (ark dev kit and mooders sectioh)?

**Comment by Neizan93** [comment] 2015-12-11 13:43
can you add twitter of devs?

**Comment by kokarn** [comment] 2015-12-11 13:52
Twitter sounds like a good plan, if they have accounts that talk mostly about development of the game. Do you have any suggested accounts? That's already tracked in #3 however.

Would you mind refining this issue a bit? What is it that you want? What is 'webpage hub' ?

**Comment by kokarn** [comment] 2015-12-16 11:27
Duplicate of #3 and #20

**Closed as completed by kokarn** 2015-12-16 11:27 UTC
